---
# Topic Names

crop_bottom: true
ros_rate: 30
debug: true
image_out_topic: "/camera/image_raw"
image_in_topic: "/cmu_rc3/camera_1/image_raw"
#image_in_topic: "/camera/image_original"
deblur: false
deblur_thresh: 500

